---
- name: Add Cilium Helm repository
  ansible.builtin.shell: "helm repo add cilium https://helm.cilium.io/"

- name: Install Cilium using Helm
  ansible.builtin.shell: "helm install cilium cilium/cilium --version 1.15.4 --namespace kube-system"

#- name: Install Cilium using Helm
#  ansible.builtin.shell: kubectl apply -n cilium-test -f https://raw.githubusercontent.com/cilium/cilium/1.15.7/examples/kubernetes/connectivity-check/connectivity-check.yaml
