---
- name: Add Argo Helm repository
  command: helm repo add argo "{{ argo_helm_repo }}"
  register: helm_repo_add
  changed_when: "'added' in helm_repo_add.stdout"

- name: Update Helm repositories
  command: helm repo update

- name: Install or upgrade Argo CD using Helm
  command: |
    helm upgrade {{ argo_release_name }} {{ argo_chart_name }} \
    --set server.service.type={{ argo_service_type }} \
    --namespace {{ argo_namespace }} \
    --install \
    --create-namespace
  register: helm_upgrade
  changed_when: "'UPGRADE' in helm_upgrade.stdout or 'INSTALL' in helm_upgrade.stdout"

- name: Display Argo CD installation status
  debug:
    msg: "{{ helm_upgrade.stdout }}"
