---
- name: Ensure that git is installed
  ansible.builtin.package:
    name: git
    state: present
  become: true

- name: Ensure that kubectl is installed
  command: "which kubectl"
  register: kubectl_check
  changed_when: False
  failed_when: kubectl_check.rc != 0

- name: Clone the AWS Cloud Controller Manager repository
  ansible.builtin.git:
    repo: https://github.com/kubernetes/cloud-provider-aws.git
    dest: /tmp/cloud-provider-aws
    version: master
    force: yes

- name: Apply AWS Cloud Controller Manager manifests
  ansible.builtin.command:
    cmd: "kubectl create -k ."
  args:
    chdir: /tmp/cloud-provider-aws/examples/existing-cluster/base


- name: Check if AWS Cloud Controller Manager pods are running
  command: "kubectl get pods -n kube-system -l app=aws-cloud-controller-manager"
  register: ccm_check
  until: ccm_check.rc == 0
  retries: 5
  delay: 30

- name: Debug Cloud Controller Manager installation result
  ansible.builtin.debug:
    var: kubectl_apply_output
