
    - name: Check if admin.conf already exists on the controller
      stat:
        path: /etc/kubernetes/admin.conf
      register: admin_conf_stat

    - name: Fetch admin.conf from managed node if not already fetched
      delegate_to: control-plane
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/admin.conf
        flat: yes
      when: not admin_conf_stat.stat.exists
