---
- name: Add the Jetstack Helm repository
  command:
    cmd: helm repo add jetstack https://charts.jetstack.io

- name: Update Helm repositories
  command:
    cmd: helm repo update

- name: Apply cert-manager CRDs
  command:
    cmd: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.crds.yaml

- name: Create cert-manager namespace
  command:
    cmd: kubectl create namespace cert-manager
  ignore_errors: yes  # Ignore if the namespace already exists

- name: Remove existing cert-manager Helm release
  command:
    cmd: helm uninstall cert-manager --namespace cert-manager
  ignore_errors: yes  # Ignore if the release does not exist

- name: Create values.yaml file for Helm installation
  ansible.builtin.copy:
    dest: /tmp/values.yaml
    content: |
      ingressShim:
        defaultIssuerName: "letsencrypt-prod"

- name: Install cert-manager using Helm
  command:
    cmd: helm install cert-manager jetstack/cert-manager --values /tmp/values.yaml --namespace cert-manager

- name: Create ClusterIssuer configuration file
  ansible.builtin.template:
    src: cluster-issuer.yaml.j2
    dest: /tmp/cluster-issuer.yaml

- name: Apply ClusterIssuer configuration to Kubernetes
  command:
    cmd: kubectl apply -f /tmp/cluster-issuer.yaml
