- name: Fetch admin.conf
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /tmp/admin.conf
  delegate_to: localhost

- name: Uninstall existing cert-manager if any
  command:
    cmd: helm uninstall cert-manager -n cert-manager
  ignore_errors: true
  environment:
    KUBECONFIG: /tmp/admin.conf

- name: Add Jetstack Helm repository
  command:
    cmd: helm repo add jetstack https://charts.jetstack.io --force-update
  environment:
    KUBECONFIG: /tmp/admin.conf

- name: Install cert-manager using Helm
  command:
    cmd: helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.16.2 --set crds.enabled=true
  environment:
    KUBECONFIG: /tmp/admin.conf

- name: Wait for cert-manager pods to be created
  shell: kubectl get pods -n cert-manager -o jsonpath='{.items[*].status.phase}' | grep -E 'Pending|Running'
  register: cert_manager_pods_status
  retries: 5
  delay: 60
  until: cert_manager_pods_status.stdout != ""
  environment:
    KUBECONFIG: /tmp/admin.conf
  failed_when: cert_manager_pods_status.stdout == ""
  success_when: cert_manager_pods_status.stdout != ""
  # This will only mark the task as complete if pods are found to be running or pending
