---
- name: Install chrony
  become: true
  apt:
    name: chrony
    state: present

- name: Start and enable chrony service
  become: true
  systemd:
    name: chrony
    state: started
    enabled: yes

- name: Synchronize time immediately with chrony
  become: true
  command: chronyc -a makestep
  notify: Restart chrony

- name: Verify time synchronization
  become: true
  command: timedatectl status
