---
- name: Join worker nodes to Kubernetes cluster
  hosts: local
  become: yes
  tasks:
    - name: Generate kubeadm join command with token
      command: kubeadm token create --print-join-command
      register: join_command_output
      changed_when: false

    - name: Set fact for join command
      set_fact:
        join_command: "{{ join_command_output.stdout }}"

- name: Join worker nodes to Kubernetes cluster
  hosts: node
  become: yes
  tasks:
    - name: Ensure kubeadm is installed
      package:
        name: kubeadm
        state: present

    - name: Check if local group is defined
      fail:
        msg: "No hosts in the local group. Please check your inventory."
      when: groups['local'] | length == 0

    - name: Join worker node to cluster
      command: "{{ hostvars[groups['local'][0]].join_command }}"  # Use the first local node in the group
      register: join_output
      ignore_errors: yes

    - name: Print join output
      debug:
        msg: "{{ join_output.stdout if join_output is defined and join_output.stdout is defined else 'Join command failed or was not executed.' }}"
