---
- name: Join worker nodes to Kubernetes cluster
  hosts: controlplane
  become: yes
  tasks:
    - name: Generate kubeadm join command with token
      command: kubeadm token create --print-join-command
      register: join_command_output
      changed_when: false

    - name: Set fact for join command
      set_fact:
        join_command: "{{ join_command_output.stdout }}"

- name: Join worker nodes to Kubernetes cluster
  hosts: workers
  become: yes
  tasks:
    - name: Ensure kubeadm is installed
      package:
        name: kubeadm
        state: present

    - name: Join worker node to cluster
      command: "{{ hostvars['master'].join_command }}"
      # Replace master0 with the appropriate name of your master node if necessary
      register: join_output
      ignore_errors: yes

    - name: Print join output
      debug:
        msg: "{{ join_output.stdout }}"
