---
- import_playbook: k8s-setup.yaml  hostlist=k8s_node
- import_playbook: time-sync.yaml  hostlist=k8s_node
- import_playbook: init-master.yml  hostlist=k8s_node
- import_playbook: first-master.yaml  hostlist=master1
- import_playbook: copy-admin-conf.yaml    hostlist=k8s_node
- import_playbook: kubectl-local.yaml    hostlist=local
- import_playbook: configure_cni.yaml hostlist=k8s_node
- import_playbook: join-master-nodes.yaml hostlist=master2:master3
- import_playbook: label-nodes.yaml hostlist=controlplane
- import_playbook: join_worker_nodes.yaml hostlist=node
- import_playbook: k8s_cert_manager.yaml  hostlist=controlplane
- import_playbook: argocd-install.yaml  hostlist=k8s_node
- import_playbook: nfs.yaml  hostlist=nfs-server
- import_playbook: nfs-setup.yaml  hostlist=k8s_node