---
- name: Apply label to all Kubernetes nodes
  hosts: master1,master2,master3
  gather_facts: false

  tasks:
    - name: Get the list of all Kubernetes nodes
      shell: kubectl get nodes | awk '{print $1}'
      register: node_list

    - name: Remove header from node list
      set_fact:
        nodes: "{{ node_list.stdout_lines[1:] }}"

    - name: Label each node with control-plane role
      loop: "{{ nodes }}"
      command: kubectl label node {{ item }} node-role.kubernetes.io/control-plane=true --overwrite

    - name: Verify the label changes
      command: kubectl get nodes --show-labels
      register: verify_output

    - name: Display verification output
      debug:
        var: verify_output.stdout_lines
