---
- name: Fetch NFS Private IP and Update Defaults
  hosts: nfs
  gather_facts: no
  vars:
    region: "ap-south-1"
    tag_name: "nfs"
    nfs_defaults_file: "/path/to/roles/nfs-setup/defaults/main.yaml"  # Adjust the path as necessary

  tasks:
    - name: Fetch NFS instance private IP from AWS
      command: >
        aws ec2 describe-instances
        --region {{ region }}
        --filters "Name=tag:Name,Values={{ tag_name }}"
        --query "Reservations[*].Instances[*].PrivateIpAddress"
        --output text
      register: nfs_ip_output

    - name: Set NFS IP fact
      set_fact:
        nfs_ip: "{{ nfs_ip_output.stdout }}"

    - name: Update NFS IP in defaults file
      lineinfile:
        path: "{{ nfs_defaults_file }}"
        regexp: "^nfs_ip:"
        line: "nfs_ip: {{ nfs_ip }}"
        backrefs: yes

    - name: Confirm updated NFS IP in defaults file
      debug:
        msg: "Updated NFS IP in {{ nfs_defaults_file }} to {{ nfs_ip }}"

